name: Docker Image CI

on:
  push:
    branches: [ main, test-workflow ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Set Time
      run: echo "TIME::$(date +'%s')" >> $GITHUB_ENV
    - name: Echo variable
      run: echo $TIME
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag balloman/random-flight-generator:$TIME
    - name: Push the Docker image
      run: docker push balloman/random-flight-generator:$TIME
