name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        TAG: $(date +%s)
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo $TAG
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag balloman/random-flight-generator:$TAG
    - name: Push the Docker image
      run: docker push balloman/random-flight-generator:$TAG
